% Script to make structure of ROI details

% Initialise structure
ROIDetails = struct();

ROINames = {
    "ROI1",...
    "ROI2",...
    "ROI3",...
    "ROI4",...
    "ROI5",...
    "ROI6",...
    "ROI7",...
    "ROI8",...
    };


Concentrations = {
    "50% PVP",...
    "40% PVP",...
    "30% PVP",...
    "20% PVP",...
    "10% PVP",...
    "5% PVP",...
    "2.5% PVP",...
    "1mM NiCl_2",...
    };


T2s = {
    126.8,...
    235.3,...
    377.1,...
    539.1,...
    693.6,...
    771.9,...
    807.3,...
    825.1,...
};


Ds = {
  0.120e-3,... 
  0.227e-3,... 
  0.382e-3,... 
  0.581e-3,... 
  0.833e-3,... 
  0.977e-3,... 
  1.032e-3,... 
  1.101e-3,... 
};

% Append to structure
ROIDetails.ROIName = ROINames;
ROIDetails.Concentration = Concentrations;
ROIDetails.T2 = T2s;
ROIDetails.D = Ds;


% Save structure as mat file
folder = "C:\Users\adam\OneDrive - University College London\UCL PhD\PhD Year 1\Projects\Noise Statistics Project\Code\Noise-Statistics-Project\New\Phantom Experiments\Imaging Data";
save([char(folder) '/ROIDetails.mat' ], 'ROIDetails')

